name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_HUB_USR: ${{ secrets.DOCKER_HUB_USR }}
        DOCKER_HUB_PSW: ${{ secrets.DOCKER_HUB_PSW }}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_HUB_USR -p $DOCKER_HUB_PSW
        echo "Fin del Login"
    
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
